version: 2.1

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/docker-publish
  docker-publish: circleci/docker-publish@0.1.3
workflows:

  # This workflow will be run on all branches but master (to test)
  build_without_publishing_job:
    jobs:
      - docker-publish/publish:
          image: vanessa/helpme
          deploy: false
          tag: latest
          registry: quay.io
          filters:
            branches:
              ignore: 
                - master
                - docs*
          after_build:
            - run:
                name: Preview Docker Tag for Build
                command: |
                   DOCKER_TAG=$(docker run vanessa/helpme:latest --version)
                   echo "Version for Docker tag is ${DOCKER_TAG}"

  # This workflow will deploy images on merge to master only
  docker_with_lifecycle:
    jobs:
      - docker-publish/publish:
          image: vanessa/helpme
          tag: latest
          registry: quay.io
          filters:
            branches:
             only: master
          after_build:
            - run:
                name: Publish Docker Tag with Helpme Version
                command: |
                   DOCKER_TAG=$(docker run vanessa/helpme:latest --version)
                   echo "Version for Docker tag is ${DOCKER_TAG}"
                   docker tag vanessa/helpme:latest quay.io/vanessa/helpme:${DOCKER_TAG}
                   docker push quay.io/vanessa/helpme:${DOCKER_TAG}
                   quay.io/vanessa/helpme:latest
